### PR TITLE
Reload gpg key files after creating them, fixes #64

### LINKED ISSUE #64: pgpSecretRing points to wrong file if not cross-building
This issue is basically the same as reported in https://github.com/olafurpg/sbt-ci-release/issues/26, but I figured out what's going on.

The `~/.gnupg/secring.gpg` file is created in the sbt session. So when sbt is started, the file doesn't exist yet. Because the file doesn't exist, [pgpSecretRing](https://github.com/sbt/sbt-pgp/blob/209e33c3ddec54f0857081db33cba81feb1880de/pgp-plugin/src/main/scala/com/typesafe/sbt/pgp/PgpSettings.scala#L106-L109) points to `~/.sbt/gpg/secring.asc`.

When cross-building (`CI_RELEASE=+publishSigned`), sbt reloads the build for every Scala version (not sure if "reload" is the right technical term here), settings are re-evaluated. Because `~/.gnupg/secring.gpg` now exists, `pgpSecretRing` gets the correct value.

If `CI_RELEASE=publishSigned`, the relaod doesn't happen.

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by olafurpg** [comment]
Released in v1.3.2 https://github.com/olafurpg/sbt-ci-release/releases/tag/v1.3.2

**Comment by lrytz** [comment]
Cool, how do you release so quickly?!?

**Comment by lrytz** [comment]
It works, I tested it with a temporary tag at scala-async (https://travis-ci.org/scala/scala-async/builds/585968808)

**Comment by olafurpg** [comment]
Nice!

**Pull request merged**
