### PR TITLE
Support SSH and Git protocol remote URLs

### PR DESCRIPTION
**Pull request by cb372**
When extracting the SCM info from the git remote URL:

* Support HTTPS, SSH and git protocols
* Support URLs with the optional `.git` suffix

### CODE REVIEW

**Comment by cb372** [comment]
A bit of context on the reason for this change: sbt-ci-release populating `scmInfo` is quite handy and we rely on it in another plugin, but we don't want to force people to clone using HTTPS protocol on developer machines.

**Comment by olafurpg** [comment]
Triggered a v1.5.3 release with this fix https://github.com/olafurpg/sbt-ci-release/releases/tag/v1.5.3

**Comment by cb372** [comment]
Thanks for the lightning-fast release! It's almost as if you know a thing or two about release automation.

**Comment by olafurpg** [comment]
haha 😅

It would be nice if the "Merge pull request" button had a checkbox to "Cut new release after merge", would automate most of the remaining manual tasks

**Pull request merged**
