### PR TITLE
Add support for GitHub Actions

### PR DESCRIPTION
**Pull request by olafurpg**
GitHub Actions (https://github.com/features/actions) offer a promising alternative to Travis CI. This PR sets up automatic CI releases for this build via GitHub Actions so that we can disable the Travis CI.

### CODE REVIEW

**Comment by alexarchambault** [comment]
@olafurpg Is it an sbt launcher generated by coursier bootstrap? I'd recommend using the [customized sbt-extras scripts](https://github.com/coursier/sbt-extras/blob/master/sbt) instead of committing a binary launcher. It downloads the latest version of the sbt-launcher itself (I mean, the launcher version is hard-coded in the script, but the script itself gets automatically updated).

**Comment by olafurpg** [comment]
@alexarchambault thank you for the suggestion! The `olafurpg/setup-java` custom action new downloads the sbt-extras script from master on every job https://github.com/olafurpg/setup-java/blob/5fbc7abe97954a5348df0397160d921ad65d2bd6/src/install.ts#L36

The coursier sbt-launcher seems to fail on sbt 1.3.x with
```
[error] java.lang.NoClassDefFoundError: lmcoursier/CoursierConfiguration
```
Any idea if it's possible to use the launcher with sbt 1.3?

**Comment by olafurpg** [comment]
GitHub Actions is looking super promising so far. It's a joy to write custom actions and the lack of caching doesn't seem to be a blocker, clean installing OpenJDK + launching sbt + compiling a bit of Scala code seems to complete in around one minute!

Screenshot 2019-09-22 at 12 19 30

The code for the custom action to install JDK + sbt is here https://github.com/olafurpg/setup-java/blob/5fbc7abe97954a5348df0397160d921ad65d2bd6/src/install.ts#L36 I think it might even work on Windows, although I haven't tested that yet.

**Comment by alexarchambault** [comment]
@olafurpg I would blame the too old sbt-coursier plugin you're relying on. But you can remove sbt-coursier altogether with sbt 1.3.x. That's unless you're using sbt-shading though, that is pulled in `project/plugins.sbt` here, but is unused apparently.

**Comment by olafurpg** [comment]
Thanks a lot for the help @alexarchambault ! I ended up installing the regular sbt-extras as `sbt` and the coursier-based one as `csbt` so people can choose which one they want. Let's give this a spin 💃

**Comment by alexarchambault** [comment]
@olafurpg You may want to add [that line](https://github.com/sbt/sbt/issues/5049#issuecomment-528960415) to remain compatible with pre-1.3 sbt versions. (Was reminded that by @eed3si9n in sbt-coursier…)

**Pull request merged**
